### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ibigbug** [Watfaq/clash-rs#59]
- [ ] inbounds
    - [x] http
    - [x] socks5
    - [x] mix port
    - [x] #73
    - [x] authentication
- [x] proxy rules
    - [x] groups
        - [x] relay
        - [x] select
        - [x] urltest
        - [x] loadbalance
        - [x] fallback
    - [x] proxies
        - [x] #161
        - [x] ss
        - [x] socks5
            - [ ] with TLS
        - [x] vmess
            - [x] ws
            - [x] aead and non-aead
        - [x] #70
        - [ ] ...
        - [ ] #190
            - [x] h2 
            - [x] #69
            - [x] tls
            - [ ] http
- [x] providers
    - [x] file
    - [x] remote
- [ ] rules
    - [x] domain_keyword
    - [x] domain_suffix
    - [x] geoip
    - [x] ipcidr
    - [x] port
    - [ ] #71
    - [x] #60
- [ ] DNS
    - [x] clients
        - [x] DoH
        - [x] DoT
        - [x] UDP/TCP
        - [x] dhcp
    - [ ] server
        - [x] #61
    - [x] HTTP query
- [ ] API
    - [x] proxies
    - [x] configs
    - [x] logs (TODO: log format)
    - [x] providers
    - [x] rules
    - [x] #62
    - [x] #63
- [x] linux support
- [x] arm support #180 
- [x] #72
- [x] #64
- [x] #65
- [ ] what else?

**Comment by greenhat616** [comment]
More transport protocols could perhaps be listed as part of the long-term plan?

* `restls`:
  * original `rust`: https://github.com/3andne/restls
  * clash go impl: https://github.com/MetaCubeX/Clash.Meta/tree/Alpha/transport/restls
* `shadow-tls`:
  * original `rust`: https://github.com/ihciah/shadow-tls
  * clash go impl: https://github.com/MetaCubeX/Clash.Meta/blob/Alpha/transport/shadowtls/
*  `v2ray-plugin`:
  * original `go`: https://github.com/shadowsocks/v2ray-plugin
  * clash go impl: https://github.com/MetaCubeX/Clash.Meta/tree/Alpha/transport/v2ray-plugin
*  `vless`:
  * original `go`: https://github.com/v2fly/v2ray-core/tree/master/proxy/vless
  * clash go impl: https://github.com/MetaCubeX/Clash.Meta/tree/Alpha/transport/vless
*  `hysteria 2`:
  * original `go`: https://github.com/apernet/hysteria
  * clash go impl: https://github.com/MetaCubeX/Clash.Meta/tree/Alpha/transport/hysteria
 
As well as more, those that have lost maintainers, or aren't used by many users, if there's a demand, integrating protocols could be considered.
* `tuic` - was desperated since Nov, 2023
  * original `go`: https://github.com/EAimTY/tuic/tree/dev
  * clash go impl: https://github.com/MetaCubeX/Clash.Meta/tree/Alpha/transport/tuic
* `gun` - gRPC Tunnel over CloudFlare
  * original `go`: https://github.com/Qv2ray/gun
  * clash go impl: https://github.com/MetaCubeX/Clash.Meta/blob/Alpha/transport/gun
* `snell` - private protocol owned by `Surge`, and the latest version is `4`, though open source impl is `1-3`
  * clash go impl: https://github.com/MetaCubeX/Clash.Meta/tree/Alpha/transport/snell
* `ssr` - was  desperated since 2017, and many patches  applied  by anouther maintainer but ended in `2019`
  *  original impl `python`: https://github.com/shadowsocksrr/shadowsocksr/tree/manyuser
  *   clash go impl: https://github.com/MetaCubeX/Clash.Meta/tree/Alpha/transport/ssr

**Comment by ibigbug** [comment]
thank you for putting this together.

I agree that there are so many protocols and transports which we'd like to have. 

i put them in a new ticket https://github.com/Watfaq/clash-rs/issues/190 and will likely to implement based off the popularity if anyone would like to ask for any one

**Comment by greenhat616** [comment]
New meta docs is here: https://github.com/keiko233/clash-nyanpasu/commit/11ae5ef4a9d94fe5c812c11a65b2ed8e667a9dc4#diff-7b5f5e4e72a6bf655ee5f197615575d1d74dd5aecf8f221f0b37ded88a3223a3
It might be useful to understand what the config field actually does

**Comment by ibigbug** [comment]
that looks good.

we have certain level of explanations of each config https://watfaq.github.io/clash-rs/clash_doc/struct.ClashConfigDef.html

that is generated from the Rust doc string.

and i agree, it can be improved

**Comment by zh-yjie** [comment]
建议添加条件编译

**Comment by ibigbug** [comment]
moved to https://github.com/Watfaq/clash-rs/issues/229

**Comment by planetoryd** [comment]
check my project https://github.com/planetoryd/nsproxy/
